### ISSUE TITLE
Running Dependency Analyser without the output path results in an exception

### ISSUE THREAD

**Issue by colinangusmackay** [diagnostica-stago/SolutionDependencyAnalyzer#1]
If you run the command and accidentally miss out the output path, then the process will spend some time building information internally, but ultimately fail (after several seconds) when it tries to write the files. 

The command should check that all needed parameters are available up front and fail with an error message that explains what when wrong.

Current output:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at SolutionDependencyAnalyzer.DotWriter.WriteProjectDependencyGraph(IDictionary`2 projectDependencies, String graphTitle) in C:\TravailGit\SolutionDependencyAnalyzer\SolutionDependencyAnalyzer\DotWriter.cs:line 27
   at SolutionDependencyAnalyzer.Program.OnExecuteAsync() in C:\TravailGit\SolutionDependencyAnalyzer\SolutionDependencyAnalyzer\Program.cs:line 52
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args)
   at SolutionDependencyAnalyzer.Program.Main(String[] args) in C:\TravailGit\SolutionDependencyAnalyzer\SolutionDependencyAnalyzer\Program.cs:line 19
   at SolutionDependencyAnalyzer.Program.<Main>(String[] args)
```

**Comment by Tradioyes** [comment]
Fixed, thanks for noticing the issue!
