### ISSUE TITLE
Win32Exception

### ISSUE THREAD

**Issue by jdvor** [diagnostica-stago/SolutionDependencyAnalyzer#97]
Every execution throws an Win32Exception around constructing the dot graph. I've tried it on several solutions.

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dot' with working directory 'C:\dev\dflex-pbs'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SolutionDependencyAnalyzer.DotWriter.WriteProjectDependencyGraph(IDictionary`2 projectDependencies, String graphTitle, Boolean createImage) in D:\TravailGit\SolutionDependencyAnalyzer\SolutionDependencyAnalyzer\DotWriter.cs:line 58
   at SolutionDependencyAnalyzer.Program.OnExecuteAsync() in D:\TravailGit\SolutionDependencyAnalyzer\SolutionDependencyAnalyzer\Program.cs:line 57
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at SolutionDependencyAnalyzer.Program.<Main>(String[] args)
```

These files are created before the exception terminates the program:
_projectsByPackage.md
packages.md
packagesByProject.md
projectDependencyGraph.dot_

`dotnet --info`
```
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.307 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by Baleine82** [comment]
Hi. Did you check that dot is correctly installed on your machine?
https://github.com/diagnostica-stago/SolutionDependencyAnalyzer#options

**Comment by jdvor** [comment]
Apparently nothing will be done.
